chipsalliance/f4pga

- requirements.txt
- source/conf.py
This PR replaces the original sphinx_materialdesing_theme with our fork of it which includes few 
modifications:
- The name changed to the "sphinx_symbiflow_theme"
- Wider margins in tables and images
- Images' and Tables' max size changed to 90%
- A lowered title header and right sidebar
- A bigger font
- Images and Tables centered by default
- A links' color changed to purple
- CSS Classes for centering/default alignment
- Added Makefile for more intuitive building process
> Adjust docs for new Sphinx Symbiflow Theme

- readthedocs.yml
This PR make RTD checkout the submodules recursively. 
Without it we are missing several chapters of the doc.
> Check out submodules recursively

- doxygen/CMakeLists.txt
- doxygen/README.md
- doxygen/c.doxyfile.in
- doxygen/doxygen.cmake
- environment.yml
- requirements.txt
- source/conf.py
This PR allows documenting C++ code using the Sphinx Framework.
The functionality is based on the Breathe plugin. This extension uses Doxygen to generate XML, which contains comments from the source code. Finally, the plugin reads Doxygen output and presents the results as Sphinx documentation. It will be useful for documenting all C++ projects including Yosys, VPR, Project X-Ray, Project Trellis, etc.
In order to avoid the regeneration every time conf.py is imported cmake has been used to generate the list of all files as dependencies and make is responsible for detecting changes in the sources files and triggering the regeneration if needed.
However, some of these projects are documented using comment styles unknown to Doxygen. As a result, the comments from the project files are not …
> Add support for documenting C++ with Sphinx

- environment.yml
- requirements.txt
- source/conf.py
This PR depends on #57 because it uses conda and should be merged after #57.
This PR adds the Symbolator to the Symbiflow Documentation.
The plugin allows generating model diagrams of Verilog files.
It can be used to obtain diagrams of sim.v files from the Symbiflow Architecture Definitions. 
In order to insert the symbols in Sphinx you need to add the follwing RST directive to you file:
<pre>
.. symbolator:: path/to/verilog/file.v
</pre>
> Generate symbols for all sim.v models

- Makefile
This commit separates the conda and sphinx building directories. This allows cleaning documentation without removing the conda environment.
> Separate conda and sphinx build directories

- requirements.txt
- source/conf.py
This commits add missing sphinx extensions used by the VTR project, and other missing dependencies which reduce the number of warnings. Additional exclude patterns disable searching for source files in undesirable directories. This PR is related to #5.
Resolves #147
> Add missing extensions and exclude patterns to reduce warnings

- requirements.txt
This commit updates the python packages versions and excludes plugins which cause that SymbiFlow documentation build is failing in RTD.
https://readthedocs.org/projects/symbiflow/builds/
> Fix documentation building

- requirements.txt
- source/conf.py
This commit adds missing `symbiflow-arch-defs` documentation.
It also bumps the required Sphinx version to ensure the same build on RTD and locally.
Resolves https://github.com/SymbiFlow/symbiflow-docs/issues/288
> Fix missing symbiflow-arch-defs documentation

- environment.yml
This PR fixes broken conda environment setup. This bug caused all dependabot builds to fail (e.g. https://readthedocs.org/projects/symbiflow/builds/14358207/). The problem was previously discussed and solved in: https://github.com/SymbiFlow/symbiflow-examples/issues/169 but it seems that it is a common issue for multiple repositories.
Signed-off-by: Paweł Czarnecki <pczarnecki@antmicro.com>
> fix env setup

- .github/sftest.json
- .github/workflows/Pipeline.yml
- docs/f4pga/Usage.md
- f4pga/__init__.py
- f4pga/argparser.py
- f4pga/flow_config.py
- f4pga/module.py
- f4pga/platforms/ql-eos-s3.json
- f4pga/platforms/ql-k4n8_fast.json
- f4pga/platforms/ql-k4n8_slow.json
- f4pga/platforms/xc7a100t.json
- f4pga/platforms/xc7a200t.json
- f4pga/platforms/xc7a50t.json
Solves #565
**THIS IS A BREAKING CHANGE:**
* `--platform` option has been removed
* Flow configurations can't refer to platfom names. Part names are used instead.
* `default_platform` flow config entry has been removed. Use `default_part` instead.
> Remove platform option

- docs/f4pga/DevNotes.md
- docs/f4pga/Usage.md
- f4pga/__init__.py
- f4pga/cache.py
- f4pga/common.py
~Symbicache~ f4cache gets updated early in `dep_differ`. This caused some false positives when reporting that a dependency "remained unchanged".
-----
Renamed symbicache to f4cache
-----
Fixed issues with reporting project status by allowing the caches to check files without updating. This however, required expicitely reporting those files those files to `F4Cache` as soon as they become available.
> Fix symbicache

- f4pga/common_modules/fasm.py
The current code can corrupt the fasm output and cause the bitstream tool to generate a faulty bitstream. This PR fixes that.
> Fix FASM append operation in FASM module

- .github/workflows/Pipeline.yml
`in-tree-builds` option seems to be incompatible with some environments that use older version of pip.
> Do not use in-tree-builds

- f4pga/flow_config.py
The override calculation algorithm skipped dependencies defined at part level in user configuration flow if they weren't limited to a stage.
> Fix stage value overrides

- .github/scripts/activate.sh
- .github/scripts/prepare_environment.sh
- f4pga-env
- f4pga/__init__.py
- f4pga/wrappers/sh/__init__.py
- f4pga/wrappers/sh/quicklogic/fasm2bels.f4pga.sh
- f4pga/wrappers/sh/quicklogic/generate_constraints.f4pga.sh
- f4pga/wrappers/sh/quicklogic/generate_libfile.f4pga.sh
- f4pga/wrappers/sh/quicklogic/ql.f4pga.sh
- f4pga/wrappers/sh/quicklogic/repack.f4pga.sh
- f4pga/wrappers/sh/quicklogic/synth.f4pga.sh
This PR changes paths to some python utilities used by deprecated QL toolchain wrappers. This change is required to eliminate inconsistency between f4pga-arch-defs packages for xc7 and eos-s3.
It is a breaking change for deprecated toolchain for QL EOS-S3 to the point of updating f4pga-arch-defs package structure.
It is cross-dependent with: https://github.com/SymbiFlow/f4pga-arch-defs/pull/2821
Signed-off-by: Paweł Czarnecki <pczarnecki@antmicro.com>
> wrappers: ql: use utility scripts from share dir

- .github/workflows/Pipeline.yml
The current output is very minimal and makes it harder to understand what went wrong in case the CI fails.
> Use extra verbose mode for f4pga CI test

- f4pga/flow_config.py
- f4pga/platforms/ql-eos-s3.json
- f4pga/platforms/ql-k4n8_fast.json
- f4pga/platforms/ql-k4n8_slow.json
- f4pga/platforms/xc7a100t.json
- f4pga/platforms/xc7a200t.json
- f4pga/platforms/xc7a50t.json
- f4pga/stage.py
The current way in which stages were defined in flow definitions made it hard read what's going on, because  module names were listed separately from their configurations. This PR replace `stages` dict with what used to be in `stage_options` and adds additional `module` field to entries that used to be listed in `stage_options` dict.
> Unify stage declarations with stage options

- f4pga/__init__.py
- f4pga/common_modules/synth.py
- f4pga/setup.py
- f4pga/wrappers/sh/__init__.py
- f4pga/wrappers/sh/quicklogic/synth.f4pga.sh
- f4pga/wrappers/sh/xc7/synth.f4pga.sh
- f4pga/wrappers/tcl/__init__.py
- f4pga/wrappers/tcl/__main__.py
- f4pga/wrappers/tcl/eos-s3/conv.f4pga.tcl
- f4pga/wrappers/tcl/eos-s3/synth.f4pga.tcl
- f4pga/wrappers/tcl/ice40/conv.f4pga.tcl
- f4pga/wrappers/tcl/ice40/synth.f4pga.tcl
- f4pga/wrappers/tcl/qlf_k4n8/conv.f4pga.tcl
- f4pga/wrappers/tcl/qlf_k4n8/synth.f4pga.tcl
- f4pga/wrappers/tcl/xc7/conv.f4pga.tcl
- f4pga/wrappers/tcl/xc7/synth.f4pga.tcl
Blocks SymbiFlow/f4pga-arch-defs#2845.
> f4pga: yosys TCL wrappers moved from f4pga-arch-defs

- f4pga/flows/common.py
It's useful sometimes to see the output from stdout when a command fails (eg. vpr)
> flows/common.sub: print stdout on error optionally

- docs/flows/f4pga.rst
Grammar fix: "The rest of the primitives is mapped..." -> "The rest of the primitives are mapped..."
> Grammar fix

- docs/conf.py
This PR addresses the following warnings:
https://github.com/chipsalliance/f4pga/actions/runs/4218861868/jobs/7323688743#step:4:12
```
WARNING: extlinks: Sphinx-6.0 will require a caption string to contain exactly one '%s' and all other '%' need to be escaped as '%%'.
WARNING: extlinks: Sphinx-6.0 will require a caption string to contain exactly one '%s' and all other '%' need to be escaped as '%%'.
WARNING: extlinks: Sphinx-6.0 will require a caption string to contain exactly one '%s' and all other '%' need to be escaped as '%%'.
WARNING: extlinks: Sphinx-6.0 will require a caption string to contain exactly one '%s' and all other '%' need to be escaped as '%%'.
WARNING: extlinks: Sphinx-6.0 will require a caption string to contain exactly one '%s' and all other '%' need to be escaped as …
```
> docs/conf: update extlinks syntax
